#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -std=c++11 -Wall -g -fexceptions -DSFML_STATIC
RESINC = 
LIBDIR = -Llibs -L/usr/include/SFML -L/usr/include/THOR
LIB = /usr/local/lib/libsfml-audio.so /usr/local/lib/libsfml-graphics.so /usr/local/lib/libsfml-network.so /usr/local/lib/libsfml-system.so /usr/local/lib/libsfml-window.so /usr/local/lib/libsfgui.so /usr/local/lib/libthor.so
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/ProjetMath

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -DRELEASE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/IHateMaths

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/ButtonPerso.o $(OBJDIR_DEBUG)/src/GraphView.o $(OBJDIR_DEBUG)/src/Game.o $(OBJDIR_DEBUG)/src/FactoryObjectPoint.o $(OBJDIR_DEBUG)/src/FactoryObjectCircle.o $(OBJDIR_DEBUG)/src/EnemyView.o $(OBJDIR_DEBUG)/src/EnemyModel.o $(OBJDIR_DEBUG)/src/Enemy.o $(OBJDIR_DEBUG)/src/EditorObject.o $(OBJDIR_DEBUG)/src/EditorCircle.o $(OBJDIR_DEBUG)/src/Editor.o $(OBJDIR_DEBUG)/src/Curves.o $(OBJDIR_DEBUG)/src/ConstrueFunction.o $(OBJDIR_DEBUG)/src/CharacterView.o $(OBJDIR_DEBUG)/src/CharacterModel.o $(OBJDIR_DEBUG)/src/GravityCircle.o $(OBJDIR_DEBUG)/src/ButtonAnim.o $(OBJDIR_DEBUG)/src/Button.o $(OBJDIR_DEBUG)/src/Axis.o $(OBJDIR_DEBUG)/src/AniSprite.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/libs/TextAreaSFML2_0.o $(OBJDIR_DEBUG)/libs/ResourcesManagerSFML2_1.o $(OBJDIR_DEBUG)/src/PhysicsObject.o $(OBJDIR_DEBUG)/src/VisitorObjectCollidable.o $(OBJDIR_DEBUG)/src/Screen_MainMenu.o $(OBJDIR_DEBUG)/src/Screen_Game.o $(OBJDIR_DEBUG)/src/Screen_Editor.o $(OBJDIR_DEBUG)/src/ScreenOption.o $(OBJDIR_DEBUG)/src/ScreenLink.o $(OBJDIR_DEBUG)/src/ScreenLevelChoiceNoChance.o $(OBJDIR_DEBUG)/src/ScreenLevelChoiceClassic.o $(OBJDIR_DEBUG)/src/ScreenLevelChoice.o $(OBJDIR_DEBUG)/src/ScreenHowTo.o $(OBJDIR_DEBUG)/src/ScreenFinish.o $(OBJDIR_DEBUG)/src/ScreenCredit.o $(OBJDIR_DEBUG)/src/Screen.o $(OBJDIR_DEBUG)/src/Point.o $(OBJDIR_DEBUG)/src/PhysicsEngine.o $(OBJDIR_DEBUG)/src/PanelEditor.o $(OBJDIR_DEBUG)/src/ObjectFactoryAbstract.o $(OBJDIR_DEBUG)/src/ManageText.o $(OBJDIR_DEBUG)/src/ManageLevel.o $(OBJDIR_DEBUG)/src/ManageFunctions.o $(OBJDIR_DEBUG)/src/LevelView.o $(OBJDIR_DEBUG)/src/LevelModel.o $(OBJDIR_DEBUG)/src/IntegralView.o $(OBJDIR_DEBUG)/src/IntegralModel.o $(OBJDIR_DEBUG)/src/Integral.o $(OBJDIR_DEBUG)/src/InfoDisplayer.o $(OBJDIR_DEBUG)/src/Hero.o $(OBJDIR_DEBUG)/libs/LineSFML2_1.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/ButtonPerso.o $(OBJDIR_RELEASE)/src/GraphView.o $(OBJDIR_RELEASE)/src/Game.o $(OBJDIR_RELEASE)/src/FactoryObjectPoint.o $(OBJDIR_RELEASE)/src/FactoryObjectCircle.o $(OBJDIR_RELEASE)/src/EnemyView.o $(OBJDIR_RELEASE)/src/EnemyModel.o $(OBJDIR_RELEASE)/src/Enemy.o $(OBJDIR_RELEASE)/src/EditorObject.o $(OBJDIR_RELEASE)/src/EditorCircle.o $(OBJDIR_RELEASE)/src/Editor.o $(OBJDIR_RELEASE)/src/Curves.o $(OBJDIR_RELEASE)/src/ConstrueFunction.o $(OBJDIR_RELEASE)/src/CharacterView.o $(OBJDIR_RELEASE)/src/CharacterModel.o $(OBJDIR_RELEASE)/src/GravityCircle.o $(OBJDIR_RELEASE)/src/ButtonAnim.o $(OBJDIR_RELEASE)/src/Button.o $(OBJDIR_RELEASE)/src/Axis.o $(OBJDIR_RELEASE)/src/AniSprite.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/libs/TextAreaSFML2_0.o $(OBJDIR_RELEASE)/libs/ResourcesManagerSFML2_1.o $(OBJDIR_RELEASE)/src/PhysicsObject.o $(OBJDIR_RELEASE)/src/VisitorObjectCollidable.o $(OBJDIR_RELEASE)/src/Screen_MainMenu.o $(OBJDIR_RELEASE)/src/Screen_Game.o $(OBJDIR_RELEASE)/src/Screen_Editor.o $(OBJDIR_RELEASE)/src/ScreenOption.o $(OBJDIR_RELEASE)/src/ScreenLink.o $(OBJDIR_RELEASE)/src/ScreenLevelChoiceNoChance.o $(OBJDIR_RELEASE)/src/ScreenLevelChoiceClassic.o $(OBJDIR_RELEASE)/src/ScreenLevelChoice.o $(OBJDIR_RELEASE)/src/ScreenHowTo.o $(OBJDIR_RELEASE)/src/ScreenFinish.o $(OBJDIR_RELEASE)/src/ScreenCredit.o $(OBJDIR_RELEASE)/src/Screen.o $(OBJDIR_RELEASE)/src/Point.o $(OBJDIR_RELEASE)/src/PhysicsEngine.o $(OBJDIR_RELEASE)/src/PanelEditor.o $(OBJDIR_RELEASE)/src/ObjectFactoryAbstract.o $(OBJDIR_RELEASE)/src/ManageText.o $(OBJDIR_RELEASE)/src/ManageLevel.o $(OBJDIR_RELEASE)/src/ManageFunctions.o $(OBJDIR_RELEASE)/src/LevelView.o $(OBJDIR_RELEASE)/src/LevelModel.o $(OBJDIR_RELEASE)/src/IntegralView.o $(OBJDIR_RELEASE)/src/IntegralModel.o $(OBJDIR_RELEASE)/src/Integral.o $(OBJDIR_RELEASE)/src/InfoDisplayer.o $(OBJDIR_RELEASE)/src/Hero.o $(OBJDIR_RELEASE)/libs/LineSFML2_1.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/libs || mkdir -p $(OBJDIR_DEBUG)/libs

after_debug: 
	cp -R  resources bin/Debug/resources

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/ButtonPerso.o: src/ButtonPerso.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ButtonPerso.cpp -o $(OBJDIR_DEBUG)/src/ButtonPerso.o

$(OBJDIR_DEBUG)/src/GraphView.o: src/GraphView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GraphView.cpp -o $(OBJDIR_DEBUG)/src/GraphView.o

$(OBJDIR_DEBUG)/src/Game.o: src/Game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Game.cpp -o $(OBJDIR_DEBUG)/src/Game.o

$(OBJDIR_DEBUG)/src/FactoryObjectPoint.o: src/FactoryObjectPoint.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FactoryObjectPoint.cpp -o $(OBJDIR_DEBUG)/src/FactoryObjectPoint.o

$(OBJDIR_DEBUG)/src/FactoryObjectCircle.o: src/FactoryObjectCircle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FactoryObjectCircle.cpp -o $(OBJDIR_DEBUG)/src/FactoryObjectCircle.o

$(OBJDIR_DEBUG)/src/EnemyView.o: src/EnemyView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EnemyView.cpp -o $(OBJDIR_DEBUG)/src/EnemyView.o

$(OBJDIR_DEBUG)/src/EnemyModel.o: src/EnemyModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EnemyModel.cpp -o $(OBJDIR_DEBUG)/src/EnemyModel.o

$(OBJDIR_DEBUG)/src/Enemy.o: src/Enemy.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Enemy.cpp -o $(OBJDIR_DEBUG)/src/Enemy.o

$(OBJDIR_DEBUG)/src/EditorObject.o: src/EditorObject.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EditorObject.cpp -o $(OBJDIR_DEBUG)/src/EditorObject.o

$(OBJDIR_DEBUG)/src/EditorCircle.o: src/EditorCircle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EditorCircle.cpp -o $(OBJDIR_DEBUG)/src/EditorCircle.o

$(OBJDIR_DEBUG)/src/Editor.o: src/Editor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Editor.cpp -o $(OBJDIR_DEBUG)/src/Editor.o

$(OBJDIR_DEBUG)/src/Curves.o: src/Curves.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Curves.cpp -o $(OBJDIR_DEBUG)/src/Curves.o

$(OBJDIR_DEBUG)/src/ConstrueFunction.o: src/ConstrueFunction.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConstrueFunction.cpp -o $(OBJDIR_DEBUG)/src/ConstrueFunction.o

$(OBJDIR_DEBUG)/src/CharacterView.o: src/CharacterView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CharacterView.cpp -o $(OBJDIR_DEBUG)/src/CharacterView.o

$(OBJDIR_DEBUG)/src/CharacterModel.o: src/CharacterModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CharacterModel.cpp -o $(OBJDIR_DEBUG)/src/CharacterModel.o

$(OBJDIR_DEBUG)/src/GravityCircle.o: src/GravityCircle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GravityCircle.cpp -o $(OBJDIR_DEBUG)/src/GravityCircle.o

$(OBJDIR_DEBUG)/src/ButtonAnim.o: src/ButtonAnim.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ButtonAnim.cpp -o $(OBJDIR_DEBUG)/src/ButtonAnim.o

$(OBJDIR_DEBUG)/src/Button.o: src/Button.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Button.cpp -o $(OBJDIR_DEBUG)/src/Button.o

$(OBJDIR_DEBUG)/src/Axis.o: src/Axis.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Axis.cpp -o $(OBJDIR_DEBUG)/src/Axis.o

$(OBJDIR_DEBUG)/src/AniSprite.o: src/AniSprite.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AniSprite.cpp -o $(OBJDIR_DEBUG)/src/AniSprite.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/libs/TextAreaSFML2_0.o: libs/TextAreaSFML2_0.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c libs/TextAreaSFML2_0.cpp -o $(OBJDIR_DEBUG)/libs/TextAreaSFML2_0.o

$(OBJDIR_DEBUG)/libs/ResourcesManagerSFML2_1.o: libs/ResourcesManagerSFML2_1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c libs/ResourcesManagerSFML2_1.cpp -o $(OBJDIR_DEBUG)/libs/ResourcesManagerSFML2_1.o

$(OBJDIR_DEBUG)/src/PhysicsObject.o: src/PhysicsObject.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PhysicsObject.cpp -o $(OBJDIR_DEBUG)/src/PhysicsObject.o

$(OBJDIR_DEBUG)/src/VisitorObjectCollidable.o: src/VisitorObjectCollidable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/VisitorObjectCollidable.cpp -o $(OBJDIR_DEBUG)/src/VisitorObjectCollidable.o

$(OBJDIR_DEBUG)/src/Screen_MainMenu.o: src/Screen_MainMenu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Screen_MainMenu.cpp -o $(OBJDIR_DEBUG)/src/Screen_MainMenu.o

$(OBJDIR_DEBUG)/src/Screen_Game.o: src/Screen_Game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Screen_Game.cpp -o $(OBJDIR_DEBUG)/src/Screen_Game.o

$(OBJDIR_DEBUG)/src/Screen_Editor.o: src/Screen_Editor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Screen_Editor.cpp -o $(OBJDIR_DEBUG)/src/Screen_Editor.o

$(OBJDIR_DEBUG)/src/ScreenOption.o: src/ScreenOption.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenOption.cpp -o $(OBJDIR_DEBUG)/src/ScreenOption.o

$(OBJDIR_DEBUG)/src/ScreenLink.o: src/ScreenLink.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenLink.cpp -o $(OBJDIR_DEBUG)/src/ScreenLink.o

$(OBJDIR_DEBUG)/src/ScreenLevelChoiceNoChance.o: src/ScreenLevelChoiceNoChance.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenLevelChoiceNoChance.cpp -o $(OBJDIR_DEBUG)/src/ScreenLevelChoiceNoChance.o

$(OBJDIR_DEBUG)/src/ScreenLevelChoiceClassic.o: src/ScreenLevelChoiceClassic.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenLevelChoiceClassic.cpp -o $(OBJDIR_DEBUG)/src/ScreenLevelChoiceClassic.o

$(OBJDIR_DEBUG)/src/ScreenLevelChoice.o: src/ScreenLevelChoice.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenLevelChoice.cpp -o $(OBJDIR_DEBUG)/src/ScreenLevelChoice.o

$(OBJDIR_DEBUG)/src/ScreenHowTo.o: src/ScreenHowTo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenHowTo.cpp -o $(OBJDIR_DEBUG)/src/ScreenHowTo.o

$(OBJDIR_DEBUG)/src/ScreenFinish.o: src/ScreenFinish.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenFinish.cpp -o $(OBJDIR_DEBUG)/src/ScreenFinish.o

$(OBJDIR_DEBUG)/src/ScreenCredit.o: src/ScreenCredit.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScreenCredit.cpp -o $(OBJDIR_DEBUG)/src/ScreenCredit.o

$(OBJDIR_DEBUG)/src/Screen.o: src/Screen.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Screen.cpp -o $(OBJDIR_DEBUG)/src/Screen.o

$(OBJDIR_DEBUG)/src/Point.o: src/Point.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Point.cpp -o $(OBJDIR_DEBUG)/src/Point.o

$(OBJDIR_DEBUG)/src/PhysicsEngine.o: src/PhysicsEngine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PhysicsEngine.cpp -o $(OBJDIR_DEBUG)/src/PhysicsEngine.o

$(OBJDIR_DEBUG)/src/PanelEditor.o: src/PanelEditor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PanelEditor.cpp -o $(OBJDIR_DEBUG)/src/PanelEditor.o

$(OBJDIR_DEBUG)/src/ObjectFactoryAbstract.o: src/ObjectFactoryAbstract.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ObjectFactoryAbstract.cpp -o $(OBJDIR_DEBUG)/src/ObjectFactoryAbstract.o

$(OBJDIR_DEBUG)/src/ManageText.o: src/ManageText.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ManageText.cpp -o $(OBJDIR_DEBUG)/src/ManageText.o

$(OBJDIR_DEBUG)/src/ManageLevel.o: src/ManageLevel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ManageLevel.cpp -o $(OBJDIR_DEBUG)/src/ManageLevel.o

$(OBJDIR_DEBUG)/src/ManageFunctions.o: src/ManageFunctions.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ManageFunctions.cpp -o $(OBJDIR_DEBUG)/src/ManageFunctions.o

$(OBJDIR_DEBUG)/src/LevelView.o: src/LevelView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/LevelView.cpp -o $(OBJDIR_DEBUG)/src/LevelView.o

$(OBJDIR_DEBUG)/src/LevelModel.o: src/LevelModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/LevelModel.cpp -o $(OBJDIR_DEBUG)/src/LevelModel.o

$(OBJDIR_DEBUG)/src/IntegralView.o: src/IntegralView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/IntegralView.cpp -o $(OBJDIR_DEBUG)/src/IntegralView.o

$(OBJDIR_DEBUG)/src/IntegralModel.o: src/IntegralModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/IntegralModel.cpp -o $(OBJDIR_DEBUG)/src/IntegralModel.o

$(OBJDIR_DEBUG)/src/Integral.o: src/Integral.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Integral.cpp -o $(OBJDIR_DEBUG)/src/Integral.o

$(OBJDIR_DEBUG)/src/InfoDisplayer.o: src/InfoDisplayer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/InfoDisplayer.cpp -o $(OBJDIR_DEBUG)/src/InfoDisplayer.o

$(OBJDIR_DEBUG)/src/Hero.o: src/Hero.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Hero.cpp -o $(OBJDIR_DEBUG)/src/Hero.o

$(OBJDIR_DEBUG)/libs/LineSFML2_1.o: libs/LineSFML2_1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c libs/LineSFML2_1.cpp -o $(OBJDIR_DEBUG)/libs/LineSFML2_1.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/libs

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/libs || mkdir -p $(OBJDIR_RELEASE)/libs

after_release: 
	cp -R  resources bin/Release/resources

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/ButtonPerso.o: src/ButtonPerso.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ButtonPerso.cpp -o $(OBJDIR_RELEASE)/src/ButtonPerso.o

$(OBJDIR_RELEASE)/src/GraphView.o: src/GraphView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GraphView.cpp -o $(OBJDIR_RELEASE)/src/GraphView.o

$(OBJDIR_RELEASE)/src/Game.o: src/Game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Game.cpp -o $(OBJDIR_RELEASE)/src/Game.o

$(OBJDIR_RELEASE)/src/FactoryObjectPoint.o: src/FactoryObjectPoint.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FactoryObjectPoint.cpp -o $(OBJDIR_RELEASE)/src/FactoryObjectPoint.o

$(OBJDIR_RELEASE)/src/FactoryObjectCircle.o: src/FactoryObjectCircle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FactoryObjectCircle.cpp -o $(OBJDIR_RELEASE)/src/FactoryObjectCircle.o

$(OBJDIR_RELEASE)/src/EnemyView.o: src/EnemyView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EnemyView.cpp -o $(OBJDIR_RELEASE)/src/EnemyView.o

$(OBJDIR_RELEASE)/src/EnemyModel.o: src/EnemyModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EnemyModel.cpp -o $(OBJDIR_RELEASE)/src/EnemyModel.o

$(OBJDIR_RELEASE)/src/Enemy.o: src/Enemy.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Enemy.cpp -o $(OBJDIR_RELEASE)/src/Enemy.o

$(OBJDIR_RELEASE)/src/EditorObject.o: src/EditorObject.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EditorObject.cpp -o $(OBJDIR_RELEASE)/src/EditorObject.o

$(OBJDIR_RELEASE)/src/EditorCircle.o: src/EditorCircle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EditorCircle.cpp -o $(OBJDIR_RELEASE)/src/EditorCircle.o

$(OBJDIR_RELEASE)/src/Editor.o: src/Editor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Editor.cpp -o $(OBJDIR_RELEASE)/src/Editor.o

$(OBJDIR_RELEASE)/src/Curves.o: src/Curves.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Curves.cpp -o $(OBJDIR_RELEASE)/src/Curves.o

$(OBJDIR_RELEASE)/src/ConstrueFunction.o: src/ConstrueFunction.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConstrueFunction.cpp -o $(OBJDIR_RELEASE)/src/ConstrueFunction.o

$(OBJDIR_RELEASE)/src/CharacterView.o: src/CharacterView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CharacterView.cpp -o $(OBJDIR_RELEASE)/src/CharacterView.o

$(OBJDIR_RELEASE)/src/CharacterModel.o: src/CharacterModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CharacterModel.cpp -o $(OBJDIR_RELEASE)/src/CharacterModel.o

$(OBJDIR_RELEASE)/src/GravityCircle.o: src/GravityCircle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GravityCircle.cpp -o $(OBJDIR_RELEASE)/src/GravityCircle.o

$(OBJDIR_RELEASE)/src/ButtonAnim.o: src/ButtonAnim.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ButtonAnim.cpp -o $(OBJDIR_RELEASE)/src/ButtonAnim.o

$(OBJDIR_RELEASE)/src/Button.o: src/Button.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Button.cpp -o $(OBJDIR_RELEASE)/src/Button.o

$(OBJDIR_RELEASE)/src/Axis.o: src/Axis.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Axis.cpp -o $(OBJDIR_RELEASE)/src/Axis.o

$(OBJDIR_RELEASE)/src/AniSprite.o: src/AniSprite.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AniSprite.cpp -o $(OBJDIR_RELEASE)/src/AniSprite.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/libs/TextAreaSFML2_0.o: libs/TextAreaSFML2_0.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c libs/TextAreaSFML2_0.cpp -o $(OBJDIR_RELEASE)/libs/TextAreaSFML2_0.o

$(OBJDIR_RELEASE)/libs/ResourcesManagerSFML2_1.o: libs/ResourcesManagerSFML2_1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c libs/ResourcesManagerSFML2_1.cpp -o $(OBJDIR_RELEASE)/libs/ResourcesManagerSFML2_1.o

$(OBJDIR_RELEASE)/src/PhysicsObject.o: src/PhysicsObject.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PhysicsObject.cpp -o $(OBJDIR_RELEASE)/src/PhysicsObject.o

$(OBJDIR_RELEASE)/src/VisitorObjectCollidable.o: src/VisitorObjectCollidable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/VisitorObjectCollidable.cpp -o $(OBJDIR_RELEASE)/src/VisitorObjectCollidable.o

$(OBJDIR_RELEASE)/src/Screen_MainMenu.o: src/Screen_MainMenu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Screen_MainMenu.cpp -o $(OBJDIR_RELEASE)/src/Screen_MainMenu.o

$(OBJDIR_RELEASE)/src/Screen_Game.o: src/Screen_Game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Screen_Game.cpp -o $(OBJDIR_RELEASE)/src/Screen_Game.o

$(OBJDIR_RELEASE)/src/Screen_Editor.o: src/Screen_Editor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Screen_Editor.cpp -o $(OBJDIR_RELEASE)/src/Screen_Editor.o

$(OBJDIR_RELEASE)/src/ScreenOption.o: src/ScreenOption.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenOption.cpp -o $(OBJDIR_RELEASE)/src/ScreenOption.o

$(OBJDIR_RELEASE)/src/ScreenLink.o: src/ScreenLink.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenLink.cpp -o $(OBJDIR_RELEASE)/src/ScreenLink.o

$(OBJDIR_RELEASE)/src/ScreenLevelChoiceNoChance.o: src/ScreenLevelChoiceNoChance.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenLevelChoiceNoChance.cpp -o $(OBJDIR_RELEASE)/src/ScreenLevelChoiceNoChance.o

$(OBJDIR_RELEASE)/src/ScreenLevelChoiceClassic.o: src/ScreenLevelChoiceClassic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenLevelChoiceClassic.cpp -o $(OBJDIR_RELEASE)/src/ScreenLevelChoiceClassic.o

$(OBJDIR_RELEASE)/src/ScreenLevelChoice.o: src/ScreenLevelChoice.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenLevelChoice.cpp -o $(OBJDIR_RELEASE)/src/ScreenLevelChoice.o

$(OBJDIR_RELEASE)/src/ScreenHowTo.o: src/ScreenHowTo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenHowTo.cpp -o $(OBJDIR_RELEASE)/src/ScreenHowTo.o

$(OBJDIR_RELEASE)/src/ScreenFinish.o: src/ScreenFinish.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenFinish.cpp -o $(OBJDIR_RELEASE)/src/ScreenFinish.o

$(OBJDIR_RELEASE)/src/ScreenCredit.o: src/ScreenCredit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScreenCredit.cpp -o $(OBJDIR_RELEASE)/src/ScreenCredit.o

$(OBJDIR_RELEASE)/src/Screen.o: src/Screen.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Screen.cpp -o $(OBJDIR_RELEASE)/src/Screen.o

$(OBJDIR_RELEASE)/src/Point.o: src/Point.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Point.cpp -o $(OBJDIR_RELEASE)/src/Point.o

$(OBJDIR_RELEASE)/src/PhysicsEngine.o: src/PhysicsEngine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PhysicsEngine.cpp -o $(OBJDIR_RELEASE)/src/PhysicsEngine.o

$(OBJDIR_RELEASE)/src/PanelEditor.o: src/PanelEditor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PanelEditor.cpp -o $(OBJDIR_RELEASE)/src/PanelEditor.o

$(OBJDIR_RELEASE)/src/ObjectFactoryAbstract.o: src/ObjectFactoryAbstract.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ObjectFactoryAbstract.cpp -o $(OBJDIR_RELEASE)/src/ObjectFactoryAbstract.o

$(OBJDIR_RELEASE)/src/ManageText.o: src/ManageText.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ManageText.cpp -o $(OBJDIR_RELEASE)/src/ManageText.o

$(OBJDIR_RELEASE)/src/ManageLevel.o: src/ManageLevel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ManageLevel.cpp -o $(OBJDIR_RELEASE)/src/ManageLevel.o

$(OBJDIR_RELEASE)/src/ManageFunctions.o: src/ManageFunctions.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ManageFunctions.cpp -o $(OBJDIR_RELEASE)/src/ManageFunctions.o

$(OBJDIR_RELEASE)/src/LevelView.o: src/LevelView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/LevelView.cpp -o $(OBJDIR_RELEASE)/src/LevelView.o

$(OBJDIR_RELEASE)/src/LevelModel.o: src/LevelModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/LevelModel.cpp -o $(OBJDIR_RELEASE)/src/LevelModel.o

$(OBJDIR_RELEASE)/src/IntegralView.o: src/IntegralView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/IntegralView.cpp -o $(OBJDIR_RELEASE)/src/IntegralView.o

$(OBJDIR_RELEASE)/src/IntegralModel.o: src/IntegralModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/IntegralModel.cpp -o $(OBJDIR_RELEASE)/src/IntegralModel.o

$(OBJDIR_RELEASE)/src/Integral.o: src/Integral.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Integral.cpp -o $(OBJDIR_RELEASE)/src/Integral.o

$(OBJDIR_RELEASE)/src/InfoDisplayer.o: src/InfoDisplayer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/InfoDisplayer.cpp -o $(OBJDIR_RELEASE)/src/InfoDisplayer.o

$(OBJDIR_RELEASE)/src/Hero.o: src/Hero.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Hero.cpp -o $(OBJDIR_RELEASE)/src/Hero.o

$(OBJDIR_RELEASE)/libs/LineSFML2_1.o: libs/LineSFML2_1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c libs/LineSFML2_1.cpp -o $(OBJDIR_RELEASE)/libs/LineSFML2_1.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/libs

virtual_all: debug release

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

